twitch-random/twitch.projet.Web.UI/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using projet_twitch.api;

namespace twitch.projet.Web.UI.Models
{
    public class DefaultDbContext : DbContext
    {
        public DefaultDbContext(DbContextOptions options) : base(options)
        {
        }

        protected DefaultDbContext()
        {
        }

        /// <summary>
        /// C'est une LISTE ! et elle sera connectée à une table en bdd
        /// </summary>
        public DbSet<Follow> Follows { get; set; }
    }
}

twitch-random/twitch.projet.Web.UI/Models/ErrorViewModel.cs
namespace twitch.projet.Web.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

twitch-random/twitch.projet.Web.UI/Models/FollowAddViewModel.cs
using projet_twitch.api;

namespace twitch.projet.Web.UI.Models
{
    public class FollowAddViewModel
    {
        public Follow UnFollow { get; set; } = null!;
    }
}

twitch-random/twitch.projet.Web.UI/Models/FollowListViewModel.cs
using projet_twitch.api;

namespace twitch.projet.Web.UI.Models
{
    public class FollowListViewModel
    {
        public List<Follow> FollowList { get; set; } = new();
    }
}

twitch-random/twitch.projet.Web.UI/Controllers/FollowController.cs
using Microsoft.AspNetCore.Mvc;
using projet_twitch.api;
using System.Linq;
using twitch.projet.Web.UI.Models;

namespace twitch.projet.Web.UI.Controllers
{
    public class FollowController : Controller
    {
        private readonly DefaultDbContext context;
        public FollowController(DefaultDbContext context)
        {
            this.context = context;
        }

        public IActionResult List()
        {
            return View();
        }

        [HttpPost]
        public IActionResult List(string followList)
        {
            var queryFollow = from follower in this.context.Follows
                                select follower;
            var queryFollowPresent = from follow in this.context.Follows
                                        where follow.PresenceTotal > 7
                                        select follow;

            List<Follow>? listFollow = null;

            if (followList == "all")
            {
                listFollow = queryFollow.ToList();
            }
            else
            {
                listFollow = queryFollowPresent.ToList();
            }
            return View("List", listFollow);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(FollowAddViewModel item)
        {
            if (ModelState.IsValid!)
            {
                ViewData["message"] = "Ajout du follower échoué !";
                return View();
            }
            else
            {
                this.context.Follows.Add(item.UnFollow);
                if (item.UnFollow.ImageProfil == null)
                {
                    item.UnFollow.ImageProfil = "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_0.jpg%27";
                }
                else
                {

                }
                this.context.SaveChanges();
                ViewData["message"] = "Ajout du follower réussi !";
                return View("List");
            }

        }
    }
}

twitch-random/twitch.projet.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using twitch.projet.Web.UI.Models;

namespace twitch.projet.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

twitch-random/twitch.projet.Web.UI/Views/Follow/Add.cshtml
@model FollowAddViewModel
﻿
<h1 class="text-center">Ajouter un nouveau follower</h1>
<br />
<p class="text-danger">@ViewData["message"]</p>
<br />
<form asp-action="Add" asp-controller="Follow" method="post">
    <div class="form-floating">
        <input asp-for="UnFollow.Surnom" type="text" class="form-control" id="ForSurnom" name="UnFollow.Surnom" placeholder="Surnom" />
        <label asp-for="UnFollow.Surnom">Surnom</label>
        <span class="text-danger" asp-validation-for="UnFollow.Surnom"></span>
    </div>
    <br />
    <div class="form-floating">
        <input type="text" class="form-control" id="ForImage" name="UnFollow.ImageProfil" placeholder="Image du profil" />
        <label for="ForImage">Image du profil</label>
    </div>
    <br />
    <button type="submit" class="form-control bg-warning">Ajout d'un Follower</button>
</form>
@section scripts
{
    <partial name="_ValidationScriptsPartial"></partial>
}

twitch-random/twitch.projet.Web.UI/Views/Follow/List.cshtml
﻿<div class="d-flex align-items-center">
    <h1>La liste des Followers</h1>
    <a class="nav-link text-dark rounded-circle " asp-area="" asp-controller="Follow" asp-action="Add">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#f0ad4e" class="bi bi-plus-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
        </svg>
    </a>
</div>
<br />
<p class="text-danger">@ViewData["message"]</p>
<br />
<div class="container">
    <form asp-action="List" asp-controller="Follow" method="post" class="row col-12">
        <select name="followList" class="col-5">
            <option selected value="all">Liste de tous les followers</option>
            <option value="bestfollower">Liste des followers présent sur plus de 70% des streams</option>
        </select>
        <button type="submit" class="btn bg-warning col-1" style="margin-left: 10px;">Afficher</button>
    </form>
    <br />
</div>


@if (Model != null)
{
    @if (Model.Count > 0)
    {
        <br />
        <table class="table table-striped table-hover">
            <tr>
                <th class="text-center">N°</th>
                <th class="text-center">Surnom</th>
                <th class="text-center">Image du Profil</th>
                <th class="text-center">Connecté ou non</th>
                <th class="text-center">Nombre de connection total</th>
            </tr>
            @foreach (var follow in this.Model)
            {
                <tr>
                    <td class="text-center">@(follow.Id)</td>
                    <td class="text-center">@(follow.Surnom)</td>
                    <td class="text-center">@(follow.ImageProfil)</td>
                    @if (follow.Connection == true)
                    {
                        <td class="text-center" data-toggle="tooltip" data-placement="bottom" title="Connecté">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#008946" class="bi bi-record-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z" />
                            </svg>
                        </td>
                    }
                    else
                    {
                        <td class="text-center" data-toggle="tooltip" data-placement="bottom" title="Déconnecté">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#e90007" class="bi bi-record-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z" />
                            </svg>
                        </td>
                    }

                    <td class="text-center">@(follow.PresenceTotal)</td>
                </tr>
            }
        </table>
    }

}
else
{
    <i>Veuillez choisir l'une des deux options ci-dessus</i>
}

twitch-random/twitch.projet.Web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

twitch-random/twitch.projet.Web.UI/Views/Shared/_Layout.cshtml
﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - twitch.projet.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/twitch.projet.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  bg-warning border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">twitch.projet.Web.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Follow" asp-action="List">Liste des followers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - twitch.projet.Web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>