twitch-random/twitch-stream.Web.UI/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;
using projet_twitch.api;

namespace twitch_stream.Models
{
    public class DefaultDbContext : DbContext
    {
        public DefaultDbContext(DbContextOptions options) : base(options)
        {
        }

        protected DefaultDbContext()
        {
        }

        /// <summary>
        /// C'est une LISTE ! et elle sera connectée à une table en bdd
        /// </summary>
        public DbSet<Streamer> Streamers { get; set; }
    }
}

twitch-random/twitch-stream.Web.UI/Models/ErrorViewModel.cs
namespace twitch_stream.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

twitch-random/twitch-stream.Web.UI/Models/StreamerAddViewModel.cs
using projet_twitch.api;

namespace twitch_stream.Models
{
    public class StreamerAddViewModel
    {
        public Streamer UnStreamer { get; set; } = null!;
    }
}

twitch-random/twitch-stream.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing.Matching;
using projet_twitch.api;
using System.Diagnostics;
using twitch_stream.Models;

namespace twitch_stream.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

twitch-random/twitch-stream.Web.UI/Controllers/StreamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing.Matching;
using System.Diagnostics;
using twitch_stream.Models;
using projet_twitch.api;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace twitch_stream.Controllers
{
    public class StreamController : Controller
    {
        private readonly DefaultDbContext context;

        public StreamController(DefaultDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var query = from item in this.context.Streamers
                        select item;

            List<Streamer> list = query.ToList();

            return View(list);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(StreamerAddViewModel item)
        {
            if (!ModelState.IsValid)
            {
                ViewData["message"] = "Ajout du stream échoué !";
                return View();
            }
            else
            {
                this.context.Streamers.Add(item.UnStreamer);
                this.context.SaveChanges();
                TempData["message"] = "Stream ajouté !";
                return RedirectToAction("Index", TempData["message"]);
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            //Streamer entity = this.context.Streamers.Find(id);
            //return View(entity);
            Streamer entity = this.context.Streamers.Find(id);
            return View(entity);

        }

        [HttpPost]
        public IActionResult Edit(Streamer Stm)
        {
            if (!ModelState.IsValid)
            {
                ViewData["message"] = "Modification du stream échoué !";
                return View();
            }
            else
            {
                var streamer = new Streamer()
                {
                    Id = Stm.Id,
                    DateS = Stm.DateS,
                    Title = Stm.Title,
                    Statut = Stm.Statut
                };
                this.context.Streamers.Update(streamer);
                this.context.SaveChanges();
                TempData["message"] = "Modification du stream effectué !";
                return RedirectToAction("Index", TempData["message"]);
            }
        }
    }
}

twitch-random/twitch-stream.Web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core%22%3Ebuilding"> Web apps with ASP.NET Core</a>.</p>
</div>

twitch-random/twitch-stream.Web.UI/Views/Shared/_Layout.cshtml
﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - twitch_stream</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/twitch_stream.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">twitch_stream</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stream" asp-action="Index">Liste des Streams</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - twitch_stream - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

twitch-random/twitch-stream.Web.UI/Views/Stream/Add.cshtml
@model StreamerAddViewModel

<h1 class="text-center">Ajouter un nouveau stream</h1>
<br />
<p class="text-danger">@ViewData["message"]</p>
<br />
<form asp-action="Add" asp-controller="Stream" method="post">
    <div class="form-floating">
        <input asp-for="UnStreamer.DateS" type="text" class="form-control" id="DateS" name="UnStreamer.DateS" placeholder="yyyy-mm-dd hh-mm-ss" />
        <label asp-for="UnStreamer.DateS">Date du stream : yyyy-mm-dd hh-mm-ss</label>
        <span class="text-danger" asp-validation-for="UnStreamer.DateS"></span>
    </div>
    <br />
    <div class="form-floating">
        <input asp-for="UnStreamer.Title" type="text" class="form-control" id="Title" name="UnStreamer.Title" placeholder="Titre du stream" />
        <label asp-for="UnStreamer.Title" for="ForTitle">Titre du stream</label>
        <span class="text-danger" asp-validation-for="UnStreamer.Title"></span>
    </div>

    <br />
    <select asp-for="UnStreamer.Statut" name="UnStreamer.Statut" class="form-control">
        <option value="Fini">Fini</option>
        <option value="En cours">En cours</option>
        <option value="A venir">A venir</option>
    </select>
    <span class="text-danger" asp-validation-for="UnStreamer.Statut"></span>
    <br />
    <button type="submit" class="form-control bg-warning">Ajout d'un Stream</button>
</form>
@section scripts
{
    <partial name="_ValidationScriptsPartial"></partial>
}

twitch-random/twitch-stream.Web.UI/Views/Stream/Edit.cshtml
@model projet_twitch.api.Streamer
﻿
<h1 class="text-center">Modifier le stream</h1>
<br />
<p class="text-danger">@ViewData["message"]</p>
<br />
<form asp-action="Edit" asp-controller="Stream" method="post">
    <div class="form-floating">
        <input asp-for="DateS" type="text" class="form-control" id="ForDateS" name="DateS" placeholder="Date du stream" value="@(Model.DateS)" />
        <label asp-for="DateS">Date du stream</label>
        <span class="text-danger" asp-validation-for="DateS"></span>
    </div>
    <br />
    <div class="form-floating">
        <input asp-for="Title" type="text" class="form-control" id="ForTitle" name="Title" placeholder="Titre du stream" value="@(Model.Title)" />
        <label asp-for="Title">Titre du stream</label>
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>

    <br />
    <select name="Statut" class="form-control">
        @if (Model.Statut == "En cours")
        {
            <option selected>@(Model.Statut)</option>
            <option value="A venir">A venir</option>
        }
        else
        {
            <option selected>@(Model.Statut)</option>
            <option value="En cours">En cours</option>
        }
    </select>
    <br />
    <button type="submit" class="form-control bg-warning">Modification du Stream</button>
</form>

twitch-random/twitch-stream.Web.UI/Views/Stream/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="d-flex align-items-center">
    <h1>La liste des Streams</h1>
    <a class="nav-link text-dark rounded-circle " asp-area="" asp-controller="Stream" asp-action="Add">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#f0ad4e" class="bi bi-plus-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
        </svg>
    </a>
</div>
<br />
<p class="text-danger">@TempData["message"]</p>
<br />
@if (this.Model.Count > 0)
{
    <table class="table table-striped table-hover">
        <tr>
            <th>DATE DU STREAM</th>
            <th>TITRE</th>
            <th>STATUT</th>
            <th>MODIFIER</th>
        </tr>
        @foreach (var item in this.Model)
        {
            <tr>
                <td>@(item.DateS)</td>
                <td>@(item.Title)</td>
                <td>@(item.Statut)</td>
                <td>
                    @if (item.Statut == "En cours" || item.Statut == "A venir")
                    {
                        @Html.ActionLink("Modifier", "Edit", new {  Id=item.Id  })
                    }
                </td>
            </tr>
        }
    </table>
}
else
{
    <i>Vous n'avez aucun Stream...</i>
}